spring:
  application:
    name: cloudplatform-config
  # 配置中心
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
  profiles:
    active: dev
  rabbitmq:
    host: 119.27.191.252
    port: 5672
    username: guest
    password: guest

eureka:
   instance:
#     ip-address: 192.168.1.241
     prefer-ip-address: true #使用IP注册
     instance-id: ${spring.cloud.client.ip-address}:${server.port}
     ##续约更新时间间隔设置5秒，m默认30s
     lease-renewal-interval-in-seconds: 5
     ##续约到期时间10秒，默认是90秒
     lease-expiration-duration-in-seconds: 10
   client:
       service-url:
         defaultZone: http://192.168.1.241:9090/eureka/

server:
  port: 8888

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
